name: Protect version.txt

on:
  pull_request:
    branches:
      - beta 

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Verify version.txt
      run: |
        if [[ "$(git diff --name-only origin/beta)" == *"version.txt"* ]]; then
          echo "Error: version.txt is modified in this PR!" >&2
          exit 1
        fi
