name: Update Version

on:
  push:
    branches:
      - beta

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: smtp://hasretagaslan@gmail.com:${{ secrets.MAIL_PASSWORD }}@smtp.gmail.com:465  # connection_url doğru şekilde belirtilmeli
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}  # E-posta adresinizi doğru girdiğinizden emin olun
          password: ${{ secrets.MAIL_PASSWORD }}  # Uygulama şifresini doğru olarak eklediğinizden emin olun
          subject: GitHub Actions Job Result
          to: hasretagaslan@gmail.com  # Alıcı adresini doğru girdiğinizden emin olun
          from: GitHub Actions <${{ secrets.MAIL_USERNAME }}>  # Gönderen adresi doğru girilmeli
          body: Build job of ${{ github.repository }} completed successfully!
          reply_to: hasretagaslan@gmail.com  # Yanıt adresini doğru girdiğinizden emin olun
          priority: normal