name: Update Version

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Send Email
        uses: hilarion5/send-mail@v1
        with:
          smtp-server: smtp.gmail.com
          smtp-port: 465
          smtp-secure: true
          from-email: hasretagaslan@gmail.com
          username: Hasret Ağaslan
          password: Hasse1998.
          subject: Test Email
          body: This is a test email sent from GitHub Actions.
         