name: Update Version

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{ secrets.MAIL_CONNECTION }}  # GitHub Secret'tan bağlantı URL'si
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: GitHub Actions Job Result
          to: hasretagaslan@gmail.com
          from: GitHub Actions <${{ secrets.MAIL_USERNAME }}>
          body: Build job of ${{ github.repository }} completed successfully!
          reply_to: hasretagaslan@gmail.com
          priority: normal
