name: Update Version

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Send Notification Email
        uses: mohammadmohsen/action-send-mail@v1
        with:
          smtp_server: smtp.gmail.com
          smtp_port: 587
          smtp_username: ${{ secrets.SMTP_USERNAME }}
          smtp_password: ${{ secrets.SMTP_PASSWORD }}
          to: recipient@example.com
          from: ${{ secrets.SMTP_USERNAME }}
          subject: "GitHub Action Started"
          body: "The GitHub Action has started for branch "