name: Update Version

on:
  push:
    branches:
      - main

jobs:
  building_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update Version
        run: |
          VERSION=$(cat version.txt)
          
          NEW_VERSION=$(echo $VERSION | awk -F'[.-]' '{printf("%s-%s.%s.%d", $1, $2, $3, $4+1)}')
          
          echo $NEW_VERSION > version.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Github Packages
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u USERNAME --password-stdin docker.pkg.github.com

    
      - name: Determine Version
        if: ${{ github.ref_name == 'beta' }}
        run: echo ::set-output name=version::$(cat version.txt)
        id: get-version
        
      - name: Determine Version
        if: ${{ github.ref_name == 'main' }}
        run: echo ::set-output name=version::$(cat version.txt)
        id: get-version
    
    